// KAMUS INGGRIS: kiri = teks Indonesia persis seperti di halaman, kanan = terjemahan Inggris.
// Menambah teks atau produk baru di index.html? Tambahkan pasangannya di sini agar ikut berganti bahasa.
// Terjemahan artikel ada di js/articles.js (blok en) dan dibuat otomatis oleh build_artikel.py.
window.KAMUS_EN = {
 "Distributor Lemari Arsip Vivorti dan Zecco | Harga Grosir | CV Cahaya Mustika": "Vivorti and Zecco Filing Cabinet Distributor | Wholesale Prices | CV Cahaya Mustika",
 "Distributor Lemari Arsip Vivorti dan Zecco": "Vivorti and Zecco Filing Cabinet Distributor",
 "Harga Grosir": "Wholesale Prices",
 "Distributor lemari arsip besi merek Vivorti dan Zecco di Malang. Filing cabinet, lemari pintu geser, rolling door, dan loker. Harga distributor, partai besar, reseller, kirim ke seluruh Indonesia.": "Distributor of Vivorti and Zecco steel filing cabinets in Malang. Filing cabinets, sliding-door cabinets, rolling doors, and lockers. Distributor prices, bulk orders, resellers, shipping across Indonesia.",
 "CV Cahaya Mustika, beranda": "CV Cahaya Mustika, home",
 "Buka menu": "Open menu",
 "Bahasa": "Language",
 "Ganti mode gelap atau terang": "Toggle dark or light mode",
 "Beranda": "Home",
 "Produk": "Products",
 "Merek Vivorti": "Vivorti brand",
 "Merek Zecco": "Zecco brand",
 "Portofolio": "Portfolio",
 "Artikel": "Articles",
 "Kontak Kami": "Contact Us",
 "Konsultasi Sekarang": "Consult Now",
 "Distributor lemari arsip merek Vivorti dan Zecco.": "Distributor of Vivorti and Zecco filing cabinets.",
 "Delapan model untuk kantor, sekolah, dan instansi. Harga distributor untuk pembelian satuan, partai besar, dan reseller, dikirim ke seluruh Indonesia.": "Eight models for offices, schools, and institutions. Distributor prices for single units, bulk orders, and resellers, delivered across Indonesia.",
 "Lihat Produk": "View Products",
 "Lemari arsip CV Cahaya Mustika": "CV Cahaya Mustika filing cabinet",
 "Harga distributor": "Distributor prices",
 "Lebih hemat untuk jumlah besar": "More savings on larger quantities",
 "Terbuka untuk reseller": "Open to resellers",
 "Kemitraan toko dan penjual": "Partnerships for stores and sellers",
 "Garansi produk": "Product warranty",
 "Perlindungan atas cacat produksi": "Coverage against manufacturing defects",
 "Kirim ke seluruh Indonesia": "Shipping across Indonesia",
 "Dikemas aman sampai tujuan": "Packed securely to your door",
 "Dua merek, banyak model lemari arsip besi": "Two brands, many steel filing cabinet models",
 "Pilih merek, lalu pilih model yang sesuai: laci, pintu ayun, pintu geser, pintu kaca, rolling door, atau loker.": "Choose a brand, then the model that fits: drawers, swing doors, sliding doors, glass doors, rolling doors, or lockers.",
 "Logo Vivorti": "Vivorti logo",
 "Logo Zecco": "Zecco logo",
 "Merek lemari arsip besi dengan model filing cabinet laci, lemari pintu ayun, dan loker. Rangka kokoh, cat powder coating, dan kunci yang aman untuk berkas penting.": "Steel filing cabinet brand with drawer filing cabinets, swing-door cabinets, and lockers. Sturdy frames, powder-coated finish, and secure locks for important files.",
 "Merek lemari arsip besi dengan model pintu geser, pintu kaca, rolling door, dan filing cabinet. Hemat area buka pintu dan luas untuk berkas.": "Steel filing cabinet brand with sliding-door, glass-door, rolling-door, and drawer models. Saves door-swing space and offers generous room for files.",
 "Vivorti VF-2 Filing cabinet 2 laci - lemari arsip besi merek Vivorti": "Vivorti VF-2 2-drawer filing cabinet - Vivorti steel filing cabinet",
 "Vivorti VF-4 Filing cabinet 4 laci - lemari arsip besi merek Vivorti": "Vivorti VF-4 4-drawer filing cabinet - Vivorti steel filing cabinet",
 "Vivorti VP-2 Lemari 2 pintu ayun - lemari arsip besi merek Vivorti": "Vivorti VP-2 2-door swing cabinet - Vivorti steel filing cabinet",
 "Vivorti VL-6 Loker 6 pintu - lemari arsip besi merek Vivorti": "Vivorti VL-6 6-door locker - Vivorti steel cabinet",
 "Zecco ZS-2 Lemari 2 pintu geser - lemari arsip besi merek Zecco": "Zecco ZS-2 2-door sliding cabinet - Zecco steel filing cabinet",
 "Zecco ZK-2 Lemari pintu geser kaca - lemari arsip besi merek Zecco": "Zecco ZK-2 glass sliding-door cabinet - Zecco steel filing cabinet",
 "Zecco ZR-3 Lemari rolling door - lemari arsip besi merek Zecco": "Zecco ZR-3 rolling door cabinet - Zecco steel filing cabinet",
 "Zecco ZF-3 Filing cabinet 3 laci - lemari arsip besi merek Zecco": "Zecco ZF-3 3-drawer filing cabinet - Zecco steel filing cabinet",
 "Filing cabinet 2 laci": "2-drawer filing cabinet",
 "Filing cabinet 4 laci": "4-drawer filing cabinet",
 "Filing cabinet 3 laci": "3-drawer filing cabinet",
 "Lemari 2 pintu ayun": "2-door swing cabinet",
 "Loker 6 pintu": "6-door locker",
 "Lemari 2 pintu geser": "2-door sliding cabinet",
 "Lemari pintu geser kaca": "Glass sliding-door cabinet",
 "Lemari rolling door": "Rolling door cabinet",
 "Filing cabinet 2 laci yang muat di bawah atau di samping meja kerja. Laci meluncur halus dan dikunci sentral.": "A 2-drawer filing cabinet that fits under or beside a desk. Drawers glide smoothly and lock centrally.",
 "Empat laci dengan kunci sentral dan rel untuk folder gantung. Pilihan utama untuk dokumen yang sering dibuka.": "Four drawers with a central lock and rails for hanging folders. A top choice for frequently accessed documents.",
 "Lemari dua pintu ayun dengan rak yang dapat diatur untuk map, box file, dan buku besar.": "Two-door swing cabinet with adjustable shelves for folders, box files, and ledgers.",
 "Loker enam pintu dengan lubang ventilasi dan kunci di setiap pintu untuk barang pribadi.": "Six-door locker with ventilation holes and a lock on every door for personal belongings.",
 "Lemari pintu geser dengan rak tinggi yang bisa diatur. Tidak memakan area buka pintu.": "Sliding-door cabinet with height-adjustable shelves. Takes no door-swing space.",
 "Pintu geser dengan panel kaca di bagian atas sehingga isi lemari terlihat tanpa membuka pintu.": "Sliding doors with a glass panel on top so the contents are visible without opening the door.",
 "Lemari dengan pintu rolling yang menggulung ke atas, cocok untuk lorong sempit dan ruang arsip padat.": "Cabinet with a rolling door that lifts upward, ideal for narrow aisles and crowded archive rooms.",
 "Filing cabinet tiga laci dengan kunci sentral, ukuran ringkas untuk berkas harian.": "Three-drawer filing cabinet with a central lock, compact for everyday files.",
 "Ukuran": "Size",
 "Kunci": "Lock",
 "Kunci sentral": "Central lock",
 "Kunci pintu": "Door lock",
 "Kunci tiap pintu": "Lock on every door",
 "Kunci rolling": "Rolling door lock",
 "Cocok untuk": "Best for",
 "Meja kerja, ruang kecil": "Desks, small rooms",
 "Kantor, notaris, klinik": "Offices, notaries, clinics",
 "Tata usaha, ruang admin": "Administration offices",
 "Sekolah, pabrik, gudang": "Schools, factories, warehouses",
 "Sekolah, dinas, gudang arsip": "Schools, government offices, archive rooms",
 "Perpustakaan, kantor, ruang tamu": "Libraries, offices, reception rooms",
 "Gudang arsip, ruang sempit": "Archive rooms, narrow spaces",
 "Kantor, sekolah, toko": "Offices, schools, shops",
 "Layanan distributor lemari arsip": "Filing cabinet distributor services",
 "Satu pemasok untuk berbagai skala pembelian, dari satu unit sampai pengadaan besar.": "One supplier for every scale of purchase, from a single unit to large procurement.",
 "Pengadaan instansi dan sekolah": "Institution and school procurement",
 "Penawaran resmi, faktur, dan pengiriman terjadwal untuk dinas, sekolah, dan perusahaan.": "Formal quotations, invoices, and scheduled delivery for government offices, schools, and companies.",
 "Reseller dan toko": "Resellers and stores",
 "Harga khusus reseller dan daftar harga terbaru. Cocok untuk toko alat kantor dan mebel.": "Special reseller pricing and an up-to-date price list. Ideal for office supply and furniture stores.",
 "Pembelian partai besar": "Bulk purchases",
 "Diskon bertingkat menurut jumlah unit, lengkap dengan pengemasan aman untuk pengiriman jauh.": "Tiered discounts by quantity, with secure packaging for long-distance shipping.",
 "Minta daftar harga distributor": "Request the distributor price list",
 "Dipercaya untuk ruang arsip yang serius": "Trusted for serious archive rooms",
 "Contoh pengadaan yang sudah kami tangani.": "Examples of procurements we have handled.",
 "Instansi pemerintah": "Government agency",
 "40 unit": "40 units",
 "24 unit": "24 units",
 "12 unit": "12 units",
 "18 unit": "18 units",
 "Kantor Pemerintah Daerah": "Regional Government Office",
 "Vivorti VF-4 untuk ruang arsip dinas, lengkap dengan pengiriman dan penataan.": "Vivorti VF-4 for the agency archive room, including delivery and setup.",
 "Pendidikan": "Education",
 "Sekolah Menengah": "Secondary School",
 "Zecco ZS-2 untuk tata usaha dan ruang guru.": "Zecco ZS-2 for the administration office and teachers' room.",
 "Layanan hukum": "Legal services",
 "Kantor Notaris": "Notary Office",
 "Vivorti VF-2 dan VF-4 untuk akta klien.": "Vivorti VF-2 and VF-4 for client deeds.",
 "Kesehatan": "Healthcare",
 "Klinik dan Rumah Sakit": "Clinics and Hospitals",
 "Zecco ZK-2 dan ZR-3 untuk rekam medis dan berkas administrasi.": "Zecco ZK-2 and ZR-3 for medical records and administrative files.",
 "Panduan singkat memilih, merawat, dan menata arsip kantor. Artikel terbaru selalu di atas.": "Short guides to choosing, maintaining, and organizing office archives. The latest article is always on top.",
 "Pertanyaan yang sering diajukan": "Frequently asked questions",
 "Belum menemukan jawabannya? Tanyakan langsung lewat WhatsApp.": "Can't find your answer? Ask us directly on WhatsApp.",
 "Apakah CV Cahaya Mustika melayani pembelian partai besar?": "Does CV Cahaya Mustika handle bulk orders?",
 "Ya. Kami melayani pengadaan untuk instansi, sekolah, dan perusahaan. Harga menyesuaikan jumlah unit, jadi semakin banyak semakin hemat.": "Yes. We handle procurement for institutions, schools, and companies. Pricing depends on the number of units, so the more you order, the more you save.",
 "Bagaimana cara menjadi reseller lemari arsip?": "How do I become a filing cabinet reseller?",
 "Hubungi kami lewat WhatsApp dan sebutkan area serta rencana pembelian Anda. Tim kami akan mengirim daftar harga distributor dan ketentuan kemitraan.": "Contact us on WhatsApp and tell us your area and purchase plans. Our team will send the distributor price list and partnership terms.",
 "Apakah pengiriman bisa ke luar kota?": "Can you ship to other cities?",
 "Bisa. Kami mengirim ke seluruh Indonesia lewat ekspedisi mitra dengan kemasan yang aman untuk lemari besi.": "Yes. We ship across Indonesia through partner couriers, with packaging suited to steel cabinets.",
 "Apa saja merek dan model yang tersedia?": "Which brands and models are available?",
 "Kami menyediakan dua merek. Vivorti: VF-2, VF-4, VP-2, dan VL-6 (filing cabinet, lemari pintu ayun, loker). Zecco: ZS-2, ZK-2, ZR-3, dan ZF-3 (pintu geser, pintu kaca, rolling door, filing cabinet).": "We offer two brands. Vivorti: VF-2, VF-4, VP-2, and VL-6 (filing cabinets, swing-door cabinets, lockers). Zecco: ZS-2, ZK-2, ZR-3, and ZF-3 (sliding doors, glass doors, rolling door, filing cabinet).",
 "Bagaimana memilih antara Vivorti dan Zecco?": "How do I choose between Vivorti and Zecco?",
 "Pilih berdasarkan model yang dibutuhkan, bukan hanya mereknya. Kirim denah ruangan dan perkiraan jumlah berkas, tim kami akan merekomendasikan model dari kedua merek yang paling pas.": "Choose by the model you need, not just the brand. Send us your room layout and estimated file volume, and our team will recommend the best fit from both brands.",
 "Apakah produk bergaransi?": "Are the products under warranty?",
 "Ya. Setiap produk mendapat garansi atas cacat produksi. Syarat dan lama garansi kami jelaskan saat penawaran, jadi Anda bisa memeriksanya sebelum memesan.": "Yes. Every product is covered against manufacturing defects. We explain the terms and duration in the quotation, so you can review them before ordering.",
 "Bingung memilih merek, model, atau jumlah?": "Not sure which brand, model, or quantity?",
 "Kirim denah ruangan dan perkiraan jumlah berkas, kami rekomendasikan modelnya.": "Send your room layout and estimated file volume, and we will recommend the right model.",
 "Kontak kami": "Contact us",
 "Ceritakan kebutuhan arsip Anda. Kami balas pada jam kerja, biasanya kurang dari satu jam.": "Tell us about your archiving needs. We reply during business hours, usually within an hour.",
 "Alamat": "Address",
 "Malang, Jawa Timur": "Malang, East Java",
 "Jam kerja": "Business hours",
 "Senin sampai Sabtu, 08.00 sampai 17.00": "Monday to Saturday, 8:00 AM to 5:00 PM",
 "Nama lengkap": "Full name",
 "Nomor WhatsApp": "WhatsApp number",
 "Anda membeli sebagai": "You are buying as",
 "Instansi atau perusahaan": "Institution or company",
 "Reseller atau toko": "Reseller or store",
 "Perorangan": "Individual",
 "Produk yang diminati": "Product of interest",
 "Belum tahu, mohon rekomendasi": "Not sure yet, please recommend",
 "Kebutuhan Anda": "Your requirements",
 "Contoh: 10 unit untuk ruang arsip 4 x 5 meter": "Example: 10 units for a 4 x 5 meter archive room",
 "Kirim lewat WhatsApp": "Send via WhatsApp",
 "CV Cahaya Mustika, distributor lemari arsip merek Vivorti dan Zecco di Malang, melayani pengiriman ke seluruh Indonesia.": "CV Cahaya Mustika, distributor of Vivorti and Zecco filing cabinets in Malang, shipping across Indonesia.",
 "Perusahaan": "Company",
 "Tanya Jawab": "FAQ",
 "© 2026 CV Cahaya Mustika. Semua hak dilindungi.": "© 2026 CV Cahaya Mustika. All rights reserved.",
 "Produk yang dibahas": "Products discussed",
 "Butuh bantuan memilih lemari arsip?": "Need help choosing a filing cabinet?",
 "Bagikan lewat WhatsApp": "Share on WhatsApp",
 "Salin tautan": "Copy link",
 "Tautan disalin": "Link copied",
 "Tautan disalin (aktif setelah website online)": "Link copied (works once the website is online)",
 "Salin tautan artikel:": "Copy the article link:",
 "Artikel lainnya": "More articles",
 "Baca artikel": "Read article",
 "Baca artikel berikutnya": "Read next article",
 "Terbaru": "Latest",
 "Baca artikel terbaru": "Read the latest article",
 "Artikel sebelumnya": "Previous articles",
 "Tampilkan artikel lainnya": "Show more articles",
 "Tanya harga Vivorti VF-2": "Ask about Vivorti VF-2 pricing",
 "Tanya harga Vivorti VF-4": "Ask about Vivorti VF-4 pricing",
 "Tanya harga Vivorti VP-2": "Ask about Vivorti VP-2 pricing",
 "Tanya harga Vivorti VL-6": "Ask about Vivorti VL-6 pricing",
 "Tanya harga Zecco ZS-2": "Ask about Zecco ZS-2 pricing",
 "Tanya harga Zecco ZK-2": "Ask about Zecco ZK-2 pricing",
 "Tanya harga Zecco ZR-3": "Ask about Zecco ZR-3 pricing",
 "Tanya harga Zecco ZF-3": "Ask about Zecco ZF-3 pricing"
};

// Teks halaman terpisah (produk, portofolio, artikel, kontak) dan beranda
Object.assign(window.KAMUS_EN, {
 "Lemari Arsip Besi Vivorti dan Zecco, 8 Model": "Vivorti and Zecco Steel Filing Cabinets, 8 Models",
 "Delapan model lemari arsip besi Vivorti dan Zecco: filing cabinet, pintu ayun, pintu geser, pintu kaca, rolling door, dan loker. Harga distributor, kirim ke seluruh Indonesia.": "Eight Vivorti and Zecco steel cabinet models: filing cabinets, swing doors, sliding doors, glass doors, rolling doors, and lockers. Distributor prices, shipped across Indonesia.",
 "Portofolio Pengadaan Lemari Arsip": "Filing Cabinet Procurement Portfolio",
 "Contoh pengadaan lemari arsip Vivorti dan Zecco untuk instansi pemerintah, sekolah, kantor notaris, klinik, dan rumah sakit.": "Examples of Vivorti and Zecco filing cabinet procurement for government agencies, schools, notary offices, clinics, and hospitals.",
 "Artikel Panduan Memilih dan Merawat Lemari Arsip": "Guides to Choosing and Maintaining Filing Cabinets",
 "Panduan singkat memilih, merawat, dan menata lemari arsip untuk kantor, sekolah, dan instansi.": "Short guides to choosing, maintaining, and organizing filing cabinets for offices, schools, and institutions.",
 "Kontak dan Pemesanan Lemari Arsip": "Contact and Filing Cabinet Orders",
 "Hubungi CV Cahaya Mustika lewat WhatsApp atau formulir untuk harga distributor, pembelian partai besar, dan kerja sama reseller lemari arsip.": "Contact CV Cahaya Mustika via WhatsApp or the form for distributor prices, bulk orders, and reseller partnerships.",
 "Pilih merek lemari arsip Anda": "Choose your filing cabinet brand",
 "Dua merek dengan banyak model: laci, pintu ayun, pintu geser, pintu kaca, rolling door, dan loker.": "Two brands with many models: drawers, swing doors, sliding doors, glass doors, rolling doors, and lockers."
});
